--- 
abstract: Make subrequests to actions in Catalyst
author: Marcus Ramberg, C<mramberg@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-SubRequest
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 5.7012
  Test::More: 0
version: 0.13
